name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mdx_truly_sane_lists 
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}